import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Download, FileText, Eye, Lock, FileSpreadsheet } from "lucide-react";
import { format } from 'date-fns';
import jsPDF from 'jspdf';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

export const generateCAPAReportContent = (capa, defect, rca, complaint) => {
  let content = `CORRECTIVE AND PREVENTIVE ACTION (CAPA) PLAN\n`;
  content += `${'='.repeat(60)}\n\n`;
  
  content += `CAPA ID: ${capa.id}\n`;
  content += `Date: ${format(new Date(capa.created_date), 'MMMM d, yyyy')}\n`;
  content += `Status: ${capa.approvalState?.replace(/_/g, ' ').toUpperCase()}\n`;
  if (capa.aiGeneratedDraft) content += `Generated by: AI-Assisted\n`;
  content += `\n`;

  // FULL TRACEABILITY SECTION
  content += `${'='.repeat(60)}\n`;
  content += `FULL TRACEABILITY CHAIN\n`;
  content += `${'='.repeat(60)}\n\n`;

  // 1. Customer Complaint / QFIR (if exists)
  if (complaint) {
    content += `1. CUSTOMER COMPLAINT / QFIR:\n`;
    content += `   -------------------------\n`;
    content += `   Ticket Number: ${complaint.ticketNumber || 'N/A'}\n`;
    content += `   Customer: ${complaint.customerName || 'N/A'}\n`;
    content += `   Film Type: ${complaint.filmType || 'N/A'}\n`;
    content += `   Issue: ${complaint.issueDescription || 'N/A'}\n`;
    content += `   Date Logged: ${complaint.dateLogged ? format(new Date(complaint.dateLogged), 'MMMM d, yyyy') : 'N/A'}\n`;
    content += `   Logged By: ${complaint.loggedBy || 'N/A'}\n`;
    content += `   Status: ${complaint.status?.replace(/_/g, ' ').toUpperCase() || 'N/A'}\n`;
    if (complaint.allocatedTo) content += `   Allocated To: ${complaint.allocatedTo}\n`;
    if (complaint.qfirData?.filledBy) {
      content += `   QFIR Filled By: ${complaint.qfirData.filledBy}\n`;
      content += `   QFIR Date: ${complaint.qfirData.filledDateIST || complaint.qfirData.filledDate || 'N/A'}\n`;
    }
    content += `\n`;
  }

  // 2. Defect Ticket
  if (defect) {
    content += `2. DEFECT TICKET:\n`;
    content += `   --------------\n`;
    content += `   Ticket ID: ${defect.ticketId || defect.id}\n`;
    content += `   Type: ${defect.defectType?.replace(/_/g, ' ')}\n`;
    content += `   Severity: ${defect.severity}\n`;
    content += `   Line: ${defect.line}\n`;
    content += `   Product: ${defect.productCode}\n`;
    content += `   Date: ${format(new Date(defect.dateTime || defect.created_date), 'MMMM d, yyyy')}\n`;
    content += `   Operator: ${defect.operator || 'N/A'}\n`;
    content += `   Status: ${defect.status?.replace(/_/g, ' ').toUpperCase() || 'N/A'}\n`;
    if (defect.immediateAction) content += `   Immediate Action: ${defect.immediateAction}\n`;
    content += `\n`;
  }

  // 3. RCA Record
  if (rca) {
    content += `3. ROOT CAUSE ANALYSIS (RCA):\n`;
    content += `   --------------------------\n`;
    content += `   RCA ID: ${rca.id}\n`;
    content += `   Analyst: ${rca.analyst}\n`;
    content += `   Status: ${rca.status?.replace(/_/g, ' ').toUpperCase()}\n`;
    content += `   Started: ${format(new Date(rca.created_date), 'MMMM d, yyyy')}\n`;
    if (rca.completedDate) content += `   Completed: ${format(new Date(rca.completedDate), 'MMMM d, yyyy')}\n`;
    
    // Root Causes Summary
    if (rca.rootCauses?.length > 0) {
      content += `\n   Identified Root Causes:\n`;
      rca.rootCauses.forEach((rc, idx) => {
        content += `   ${idx + 1}. ${rc.cause || rc}\n`;
        if (rc.category) content += `      Category: ${rc.category}\n`;
        if (rc.confidence) content += `      Confidence: ${rc.confidence}%\n`;
      });
    }
    
    // 5-Why Summary
    if (rca.fiveWhyTree?.length > 0) {
      content += `\n   5-Why Analysis:\n`;
      rca.fiveWhyTree.forEach(why => {
        if (why.answer) content += `   Why ${why.level}: ${why.answer}\n`;
      });
    }
    content += `\n`;
  }

  // 4. This CAPA
  content += `4. CAPA (THIS DOCUMENT):\n`;
  content += `   ---------------------\n`;
  content += `   CAPA ID: ${capa.id}\n`;
  content += `   Created: ${format(new Date(capa.created_date), 'MMMM d, yyyy')}\n`;
  content += `   Status: ${capa.approvalState?.replace(/_/g, ' ').toUpperCase()}\n`;
  content += `   Corrective Actions: ${capa.correctiveActions?.length || 0}\n`;
  content += `   Preventive Actions: ${capa.preventiveActions?.length || 0}\n`;
  if (capa.fmea?.rpn) content += `   RPN: ${capa.fmea.rpn}\n`;
  content += `\n`;

  content += `${'='.repeat(60)}\n\n`;
  
  // Implementation Strategy
  if (capa.implementationStrategy) {
    content += `IMPLEMENTATION STRATEGY:\n`;
    content += `------------------------\n`;
    content += `${capa.implementationStrategy}\n\n`;
  }
  
  // FMEA Risk Assessment
  if (capa.fmea) {
    content += `RISK ASSESSMENT (FMEA):\n`;
    content += `-----------------------\n`;
    content += `Severity: ${capa.fmea.severity}/10\n`;
    content += `Occurrence: ${capa.fmea.occurrence}/10\n`;
    content += `Detection: ${capa.fmea.detection}/10\n`;
    content += `Risk Priority Number (RPN): ${capa.fmea.rpn}\n`;
    if (capa.fmea.notes) content += `Notes: ${capa.fmea.notes}\n`;
    
    // AI Analysis details
    if (capa.fmea.aiAnalysis) {
      content += `\nAI Analysis:\n`;
      if (capa.fmea.aiAnalysis.severityJustification) 
        content += `  Severity Reasoning: ${capa.fmea.aiAnalysis.severityJustification}\n`;
      if (capa.fmea.aiAnalysis.occurrenceJustification) 
        content += `  Occurrence Reasoning: ${capa.fmea.aiAnalysis.occurrenceJustification}\n`;
      if (capa.fmea.aiAnalysis.detectionJustification) 
        content += `  Detection Reasoning: ${capa.fmea.aiAnalysis.detectionJustification}\n`;
      if (capa.fmea.aiAnalysis.projectedRPNAfterActions)
        content += `  Projected RPN After CAPA: ${capa.fmea.aiAnalysis.projectedRPNAfterActions}\n`;
      if (capa.fmea.aiAnalysis.overallAssessment)
        content += `  Overall Assessment: ${capa.fmea.aiAnalysis.overallAssessment}\n`;
    }
    
    // Failure Modes
    if (capa.fmea.failureModes?.length > 0) {
      content += `\nFailure Modes:\n`;
      capa.fmea.failureModes.forEach((fm, idx) => {
        content += `  ${idx + 1}. ${fm.mode}\n`;
        content += `     Effect: ${fm.effect}\n`;
        content += `     Cause: ${fm.cause}\n`;
        content += `     S=${fm.severity} O=${fm.occurrence} D=${fm.detection} RPN=${fm.rpn}\n`;
      });
    }
    
    // Recommended Controls
    if (capa.fmea.recommendedControls?.length > 0) {
      content += `\nRecommended Controls:\n`;
      capa.fmea.recommendedControls.forEach((ctrl, idx) => {
        content += `  ${idx + 1}. ${ctrl.control}\n`;
        content += `     Type: ${ctrl.type} | Expected Impact: ${ctrl.expectedImpact}\n`;
      });
    }
    content += `\n`;
  }
  
  // Corrective Actions
  if (capa.correctiveActions && capa.correctiveActions.length > 0) {
    content += `CORRECTIVE ACTIONS:\n`;
    content += `===================\n\n`;
    capa.correctiveActions.forEach((action, idx) => {
      content += `CA-${idx + 1}:\n`;
      content += `Action: ${action.action}\n`;
      content += `Owner: ${action.owner} (${action.ownerRole || 'N/A'})\n`;
      content += `Due Date: ${action.dueDate ? format(new Date(action.dueDate), 'MMMM d, yyyy') : 'Not set'}\n`;
      content += `Status: ${action.status?.replace(/_/g, ' ').toUpperCase()}\n`;
      if (action.complexity) content += `Complexity: ${action.complexity}\n`;
      if (action.verificationMethod) content += `Verification: ${action.verificationMethod}\n`;
      if (action.linkedRootCause) content += `Addresses: ${action.linkedRootCause}\n`;
      if (action.estimatedCost) content += `Est. Cost: ${action.estimatedCost}\n`;
      if (action.completionDate) content += `Completed: ${format(new Date(action.completionDate), 'MMMM d, yyyy')}\n`;
      content += `\n`;
    });
  }
  
  // Preventive Actions
  if (capa.preventiveActions && capa.preventiveActions.length > 0) {
    content += `PREVENTIVE ACTIONS:\n`;
    content += `===================\n\n`;
    capa.preventiveActions.forEach((action, idx) => {
      content += `PA-${idx + 1}:\n`;
      content += `Action: ${action.action}\n`;
      content += `Owner: ${action.owner} (${action.ownerRole || 'N/A'})\n`;
      content += `Due Date: ${action.dueDate ? format(new Date(action.dueDate), 'MMMM d, yyyy') : 'Not set'}\n`;
      content += `Status: ${action.status?.replace(/_/g, ' ').toUpperCase()}\n`;
      if (action.complexity) content += `Complexity: ${action.complexity}\n`;
      if (action.systemImpact) content += `System Impact: ${action.systemImpact}\n`;
      if (action.trainingRequired) content += `Training Required: Yes\n`;
      if (action.documentationUpdate) content += `Documentation Update: ${action.documentationUpdate}\n`;
      if (action.completionDate) content += `Completed: ${format(new Date(action.completionDate), 'MMMM d, yyyy')}\n`;
      content += `\n`;
    });
  }
  
  // SOP Recommendations
  if (capa.sopRecommendations) {
    content += `SOP RECOMMENDATIONS:\n`;
    content += `====================\n\n`;
    
    if (capa.sopRecommendations.sopUpdatesNeeded?.length > 0) {
      content += `SOPs to Update:\n`;
      capa.sopRecommendations.sopUpdatesNeeded.forEach((sop, idx) => {
        content += `${idx + 1}. ${sop.existingSOPTitle} (${sop.priority} priority)\n`;
        content += `   Changes: ${sop.requiredChanges}\n`;
      });
      content += `\n`;
    }
    
    if (capa.sopRecommendations.newSOPsNeeded?.length > 0) {
      content += `New SOPs Needed:\n`;
      capa.sopRecommendations.newSOPsNeeded.forEach((sop, idx) => {
        content += `${idx + 1}. ${sop.suggestedTitle} (${sop.priority} priority)\n`;
        content += `   Purpose: ${sop.purpose}\n`;
      });
      content += `\n`;
    }
    
    if (capa.sopRecommendations.trainingMaterialsNeeded?.length > 0) {
      content += `Training Materials:\n`;
      capa.sopRecommendations.trainingMaterialsNeeded.forEach((material, idx) => {
        content += `${idx + 1}. ${material}\n`;
      });
      content += `\n`;
    }
  }
  
  // Success Criteria
  if (capa.successCriteria?.length > 0) {
    content += `SUCCESS CRITERIA:\n`;
    content += `=================\n`;
    capa.successCriteria.forEach((criterion, idx) => {
      content += `${idx + 1}. ${criterion}\n`;
    });
    content += `\n`;
  }
  
  // Effectiveness Check
  if (capa.effectivenessCheck) {
    content += `EFFECTIVENESS CHECK:\n`;
    content += `====================\n`;
    if (capa.effectivenessCheck.checkDate) {
      content += `Check Date: ${format(new Date(capa.effectivenessCheck.checkDate), 'MMMM d, yyyy')}\n`;
    }
    content += `Effective: ${capa.effectivenessCheck.effective ? 'YES' : 'NO'}\n`;
    if (capa.effectivenessCheck.notes) content += `Notes: ${capa.effectivenessCheck.notes}\n`;
    
    // Metrics comparison
    if (capa.effectivenessCheck.metricsBefore || capa.effectivenessCheck.metricsAfter) {
      content += `\nMetrics Comparison:\n`;
      content += `  Before -> After\n`;
      if (capa.effectivenessCheck.metricsBefore?.defectRate || capa.effectivenessCheck.metricsAfter?.defectRate)
        content += `  Defect Rate: ${capa.effectivenessCheck.metricsBefore?.defectRate || 'N/A'}% -> ${capa.effectivenessCheck.metricsAfter?.defectRate || 'N/A'}%\n`;
      if (capa.effectivenessCheck.metricsBefore?.fpy || capa.effectivenessCheck.metricsAfter?.fpy)
        content += `  First Pass Yield: ${capa.effectivenessCheck.metricsBefore?.fpy || 'N/A'}% -> ${capa.effectivenessCheck.metricsAfter?.fpy || 'N/A'}%\n`;
      if (capa.effectivenessCheck.metricsBefore?.customerComplaints || capa.effectivenessCheck.metricsAfter?.customerComplaints)
        content += `  Customer Complaints: ${capa.effectivenessCheck.metricsBefore?.customerComplaints || 'N/A'} -> ${capa.effectivenessCheck.metricsAfter?.customerComplaints || 'N/A'}\n`;
    }
    content += `\n`;
  }
  
  // Signatures
  if (capa.signatures?.length > 0) {
    content += `APPROVALS:\n`;
    content += `==========\n`;
    capa.signatures.forEach(sig => {
      content += `${sig.role}: ${sig.signedBy} (${format(new Date(sig.signedDate), 'MMMM d, yyyy')})\n`;
      if (sig.comments) content += `  Comments: ${sig.comments}\n`;
    });
    content += `\n`;
  }
  
  content += `\n${'='.repeat(60)}\n`;
  content += `Generated: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST\n`;
  content += `End of CAPA Plan\n`;
  
  return content;
};

export const downloadCAPAReport = (capa, defect, rca, complaint) => {
  const content = generateCAPAReportContent(capa, defect, rca, complaint);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `CAPA-${capa.id?.slice(0, 8) || 'draft'}-${format(new Date(), 'yyyy-MM-dd')}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

const downloadPDFReport = (capa, defect, rca, complaint) => {
  const doc = new jsPDF();
  let yPos = 20;
  const lineHeight = 7;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;

  const checkPageBreak = (neededSpace = 20) => {
    if (yPos + neededSpace > pageHeight - margin) {
      doc.addPage();
      yPos = 20;
    }
  };

  const addText = (text, size = 10, style = 'normal') => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    const lines = doc.splitTextToSize(text, 170);
    checkPageBreak(lines.length * lineHeight);
    doc.text(lines, 20, yPos);
    yPos += lines.length * lineHeight;
  };

  // Title
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, 210, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text('CAPA REPORT', 20, 20);
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 27);
  yPos = 40;
  doc.setTextColor(0, 0, 0);

  // CAPA Summary
  addText('CAPA SUMMARY', 14, 'bold');
  yPos += 3;
  addText(`CAPA ID: ${capa.id?.slice(0, 12)}`, 10);
  addText(`Status: ${capa.approvalState?.replace(/_/g, ' ').toUpperCase()}`, 10);
  addText(`Created: ${format(new Date(capa.created_date), 'MMMM d, yyyy')}`, 10);
  if (capa.aiGeneratedDraft) addText('Generated by: AI-Assisted', 10);
  yPos += 5;

  // Traceability
  if (complaint || defect || rca) {
    checkPageBreak(30);
    addText('TRACEABILITY CHAIN', 12, 'bold');
    yPos += 3;
    
    if (complaint) {
      addText(`Customer Complaint: ${complaint.ticketNumber}`, 10);
      addText(`  Customer: ${complaint.customerName}`, 9);
      addText(`  Issue: ${complaint.issueDescription?.slice(0, 100)}`, 9);
    }
    if (defect) {
      addText(`Defect: ${defect.ticketId || defect.id}`, 10);
      addText(`  Type: ${defect.defectType?.replace(/_/g, ' ')} (${defect.severity})`, 9);
      addText(`  Line: ${defect.line}, Product: ${defect.productCode}`, 9);
    }
    if (rca) {
      addText(`RCA: ${rca.id.slice(0, 12)}`, 10);
      addText(`  Analyst: ${rca.analyst}`, 9);
      addText(`  Root Causes: ${rca.rootCauses?.length || 0} identified`, 9);
    }
    yPos += 5;
  }

  // FMEA
  if (capa.fmea) {
    checkPageBreak(30);
    addText('RISK ASSESSMENT (FMEA)', 12, 'bold');
    yPos += 3;
    addText(`Severity: ${capa.fmea.severity}/10`, 10);
    addText(`Occurrence: ${capa.fmea.occurrence}/10`, 10);
    addText(`Detection: ${capa.fmea.detection}/10`, 10);
    addText(`RPN: ${capa.fmea.rpn}`, 10, 'bold');
    if (capa.fmea.notes) addText(`Notes: ${capa.fmea.notes}`, 9);
    yPos += 5;
  }

  // Corrective Actions
  if (capa.correctiveActions?.length > 0) {
    checkPageBreak(40);
    addText('CORRECTIVE ACTIONS', 12, 'bold');
    yPos += 3;
    capa.correctiveActions.forEach((action, idx) => {
      checkPageBreak(25);
      addText(`CA-${idx + 1}: ${action.action}`, 10, 'bold');
      addText(`  Owner: ${action.owner} (${action.ownerRole || 'N/A'})`, 9);
      addText(`  Due: ${action.dueDate ? format(new Date(action.dueDate), 'MMM d, yyyy') : 'N/A'} | Status: ${action.status?.replace(/_/g, ' ').toUpperCase()}`, 9);
      if (action.verificationMethod) addText(`  Verification: ${action.verificationMethod}`, 9);
      yPos += 2;
    });
    yPos += 3;
  }

  // Preventive Actions
  if (capa.preventiveActions?.length > 0) {
    checkPageBreak(40);
    addText('PREVENTIVE ACTIONS', 12, 'bold');
    yPos += 3;
    capa.preventiveActions.forEach((action, idx) => {
      checkPageBreak(25);
      addText(`PA-${idx + 1}: ${action.action}`, 10, 'bold');
      addText(`  Owner: ${action.owner} (${action.ownerRole || 'N/A'})`, 9);
      addText(`  Due: ${action.dueDate ? format(new Date(action.dueDate), 'MMM d, yyyy') : 'N/A'} | Status: ${action.status?.replace(/_/g, ' ').toUpperCase()}`, 9);
      if (action.systemImpact) addText(`  System Impact: ${action.systemImpact}`, 9);
      yPos += 2;
    });
    yPos += 3;
  }

  // Effectiveness Check
  if (capa.effectivenessCheck && capa.effectivenessCheck.effective !== null) {
    checkPageBreak(30);
    addText('EFFECTIVENESS CHECK', 12, 'bold');
    yPos += 3;
    addText(`Result: ${capa.effectivenessCheck.effective ? 'EFFECTIVE' : 'NOT EFFECTIVE'}`, 10, 'bold');
    if (capa.effectivenessCheck.checkDate) {
      addText(`Check Date: ${format(new Date(capa.effectivenessCheck.checkDate), 'MMM d, yyyy')}`, 9);
    }
    if (capa.effectivenessCheck.notes) addText(`Notes: ${capa.effectivenessCheck.notes}`, 9);
  }

  doc.save(`CAPA-${capa.id?.slice(0, 8)}-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
};

export default function CAPAExporter({ capa, defect, rca, complaint }) {
  const [previewOpen, setPreviewOpen] = useState(false);
  const [exportFormat, setExportFormat] = useState('txt');
  
  const isClosed = capa.approvalState === 'closed';

  const generateContent = () => generateCAPAReportContent(capa, defect, rca, complaint);

  const handleExport = () => {
    if (exportFormat === 'pdf') {
      downloadPDFReport(capa, defect, rca, complaint);
    } else {
      downloadCAPAReport(capa, defect, rca, complaint);
    }
  };
  
  return (
    <>
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-blue-600" />
              CAPA Document
            </CardTitle>
            <Badge className={isClosed ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'}>
              {isClosed ? 'Ready for Download' : 'Preview Only'}
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-gray-600">
            {isClosed 
              ? 'CAPA is closed. You can download the complete report in PDF or TXT format.'
              : 'CAPA must be closed before downloading. You can preview the report now.'}
          </p>

          {isClosed && (
            <div>
              <label className="text-sm font-medium text-gray-700 mb-2 block">Export Format</label>
              <Select value={exportFormat} onValueChange={setExportFormat}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="pdf">PDF Report</SelectItem>
                  <SelectItem value="txt">Text Report</SelectItem>
                </SelectContent>
              </Select>
            </div>
          )}

          <div className="flex gap-3">
            <Button 
              onClick={() => setPreviewOpen(true)} 
              variant="outline"
              className="flex-1"
            >
              <Eye className="w-4 h-4 mr-2" />
              Preview Report
            </Button>

            <Button 
              onClick={handleExport} 
              className={`flex-1 ${isClosed ? 'bg-blue-600 hover:bg-blue-700' : 'bg-gray-400 cursor-not-allowed'}`}
              disabled={!isClosed}
            >
              {isClosed ? (
                <>
                  <Download className="w-4 h-4 mr-2" />
                  Download {exportFormat.toUpperCase()}
                </>
              ) : (
                <>
                  <Lock className="w-4 h-4 mr-2" />
                  Close CAPA to Download
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Preview Dialog */}
      <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
        <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-blue-600" />
              CAPA Report Preview
            </DialogTitle>
          </DialogHeader>
          <div className="bg-gray-50 p-4 rounded-lg border">
            <pre className="text-xs font-mono whitespace-pre-wrap text-gray-800">
              {generateContent()}
            </pre>
          </div>
          <div className="flex justify-end gap-3 mt-4">
            <Button variant="outline" onClick={() => setPreviewOpen(false)}>
              Close
            </Button>
            {isClosed && (
              <Button onClick={handleExport} className="bg-blue-600 hover:bg-blue-700">
                <Download className="w-4 h-4 mr-2" />
                Download
              </Button>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}